class tcb {
	tag = "tcb";
	class functions {
		class actionCarry { file="feats\revive\ais\actionCarry.sqf"; };
		class actionCondition { file="feats\revive\ais\actionCondition.sqf"; };
		class actionDrag { file="feats\revive\ais\actionDrag.sqf"; };
		class actionDrop { file="feats\revive\ais\actionDrop.sqf"; };
		class actionHeal { file="feats\revive\ais\actionHeal.sqf"; };
		class actionHelp { file="feats\revive\ais\actionHelp.sqf"; };
		class actionLoad { file="feats\revive\ais\actionLoad.sqf"; };
		class actionUnload { file="feats\revive\ais\actionUnload.sqf"; };
		class actionVehHeal { file="feats\revive\ais\actionVehHeal.sqf"; };
		class callHelp { file="feats\revive\ais\callHelp.sqf"; };
		class deadCam { file="feats\revive\ais\deadCam.sqf"; };
		class deadCamQuote { file="feats\revive\ais\deadCamQuote.sqf"; };
		class drawIcon3D { file="feats\revive\ais\drawIcon3D.sqf"; };
		class dynamicText { file="feats\revive\ais\dynamicText.sqf"; };
		class gotItem { file="feats\revive\ais\gotItem.sqf"; };
		class handleDamage { file="feats\revive\ais\handleDamage.sqf"; };
		class healAnimEH { file="feats\revive\ais\healAnimEH.sqf"; };
		class healCheck { file="feats\revive\ais\healCheck.sqf"; };
		class helpAnimEH { file="feats\revive\ais\helpAnimEH.sqf"; };
		class keyUnbind { file="feats\revive\ais\keyUnbind.sqf"; };
		class progressBar { file="feats\revive\ais\progressBar.sqf"; };
		class progressBarInit { file="feats\revive\ais\progressBarInit.sqf"; };
		class removeFaks { file="feats\revive\ais\removeFaks.sqf"; };
		class removeHealEquipment { file="feats\revive\ais\removeHealEquipment.sqf"; };
		class sfxBloodParticles { file="feats\revive\ais\sfxBloodParticles.sqf"; };
		class sfxImpactEffect { file="feats\revive\ais\sfxImpactEffect.sqf"; };
		class sfxInjuredEffect { file="feats\revive\ais\sfxInjuredEffect.sqf"; };
		class spawnHealEquipment { file="feats\revive\ais\spawnHealEquipment.sqf"; };
		class stopUnitBleeding { file="feats\revive\ais\stopUnitBleeding.sqf"; };
	};
};
