class mapTracker {
	colorNeedRevive[]={1, 0.41, 0, 1};
	colorEast[]={0.5, 0, 0};
	colorWest[]={0, 0.3, 0.6};
	colorInd[]={0, 0.5, 0};
	colorCiv[]={0.4, 0, 0.5};
    colorDft[]={0.7, 0.6, 0};
    sizeMan = 22;
    sizeLandVehicle = 28;
    sizeAir = 28;
    sizeShip = 26;
    shadow = 1;
    textSize = 0.05;
    textFont = "puristaMedium";
    textOffset = "right";
    gpsDist = 1000;
    class roleDescriptions {
    	hq = "HQ";
    	sl = "Squad Leader";
    	tl = "Team Leader";
    	medic ="Combat Life Saver";
    	lmg = "Light Machine Gunner";
    	hmg = "Heavy Machine Gunner";
    	assHMG = "Assistant HMG";
    	at ="Missile Specialist";
    	assAT = "Assistant AT";
    	sniper = "Sniper";
    	marksman = "Marksman";
    	repair = "Repair Specialist";
    	demo = "Explosives Specialist";
    	engineer = "Engineer";
    	grenadier ="Grenadier";
    	rifleman = "Rifleman";
    	jtac = "Fire Support Specialist";
    	hPilot = "Helicopter Pilot";
    	jPilot = "Fighter Pilot";
    	crew = "Crew";
    	mortar = "Mortar Gunner";
    	uavOp = "UAV Operator";
    	spotter = "Spotter";
    };
};
