#include "baseDefence\_cfgRemoteExec.hpp"
#include "baseLight\_cfgRemoteExec.hpp"
#include "curator\_cfgRemoteExec.hpp"
#include "environment\_cfgRemoteExec.hpp"
#include "ia\SIDE\_cfgRemoteExec.hpp"
#include "memberData\_cfgRemoteExec.hpp"
#include "vehicleRestrictions\_cfgRemoteExec.hpp"
