class revive {
	tag = "revive";
	class functions {
		class headlessDestroy { file="feats\revive\headlessDestroy.sqf"; };
		class headlessInit  { file="feats\revive\headlessInit.sqf"; };
		class headlessJoin { file="feats\revive\headlessJoin.sqf"; };
		class playerDestroy { file="feats\revive\playerDestroy.sqf"; };
		class playerInit  { file="feats\revive\playerInit.sqf"; };
		class playerJoin { file="feats\revive\playerJoin.sqf"; };
		class serverDestroy { file="feats\revive\serverDestroy.sqf"; };
		class serverInit  { file="feats\revive\serverInit.sqf"; };
		class serverJoin { file="feats\revive\serverJoin.sqf"; };
		class actionCarry { file="feats\revive\actions\carry.sqf"; };
		class actionCondition { file="feats\revive\actions\condition.sqf"; };
		class actionDrag { file="feats\revive\actions\drag.sqf"; };
		class actionDrop { file="feats\revive\actions\drop.sqf"; };
		class actionHeal { file="feats\revive\actions\heal.sqf"; };
		class actionHelp { file="feats\revive\actions\help.sqf"; };
		class actionLoad { file="feats\revive\actions\load.sqf"; };
		class actionUnload { file="feats\revive\actions\unload.sqf"; };
		class actionVehHeal { file="feats\revive\actions\vehHeal.sqf"; };
		class addBleeding { file="feats\revive\addBleeding.sqf"; };
		class callHelp { file="feats\revive\callHelp.sqf"; };
		class deadCam { file="feats\revive\deadCam.sqf"; };
		class deadCamQuote { file="feats\revive\deadCamQuote.sqf"; };
		class doHeal { file="feats\revive\doHeal.sqf"; };
		class drawIcon3D { file="feats\revive\drawIcon3D.sqf"; };
		class dynamicText { file="feats\revive\dynamicText.sqf"; };
		class gotItem { file="feats\revive\gotItem.sqf"; };
		class handleDamage { file="feats\revive\handleDamage.sqf"; };
		class healAnimEH { file="feats\revive\healAnimEH.sqf"; };
		class helpAnimEH { file="feats\revive\helpAnimEH.sqf"; };
		class keyUnbind { file="feats\revive\keyUnbind.sqf"; };
		class progressBar { file="feats\revive\progressBar.sqf"; };
		class progressBarInit { file="feats\revive\progressBarInit.sqf"; };
		class removeFaks { file="feats\revive\removeFaks.sqf"; };
		class removeHealEquipment { file="feats\revive\removeHealEquipment.sqf"; };
		class sfxBloodParticles { file="feats\revive\sfxBloodParticles.sqf"; };
		class sfxImpactEffect { file="feats\revive\sfxImpactEffect.sqf"; };
		class sfxInjuredEffect { file="feats\revive\sfxInjuredEffect.sqf"; };
		class stopBleeding { file="feats\revive\stopBleeding.sqf"; };
	};
};
