#define T_BV_tuvanaka [["heliSmall", 		20, "BV_lb1"],\
                       ["heliSmallArmed", 	20, "BV_lb2"],\
                       ["heliMedium", 		20, "BV_bh1"],\
                       ["heliMedEvac", 		20, "BV_bh2"],\
                       ["planeTransport", 	20, "BV_c130"],\
                       ["planeAA", 			20, "BV_aajet"],\
                       ["uav",	 			20, "BV_uav"],\
                       ["planeCAS", 		20, "BV_a10"],\
                       ["carArmed",			20, "BV_hmmv1"],\
                       ["carArmed",			20, "BV_hmmv2"],\
                       ["car", 				20, "BV_hmmv3"],\
                       ["car", 				20, "BV_hmmv4"],\
                       ["carArmed",			20, "BV_fobhmmv1"],\
                       ["carArmed",			20, "BV_fobhmmv2"],\
                       ["quad", 			20, "BV_quadI1"],\
                       ["quad", 			20, "BV_quadI2"],\
                       ["quad", 			20, "BV_quadI3"],\
                       ["quad", 			20, "BV_quadI4"],\
                       ["quad", 			20, "BV_quadH1"],\
                       ["quad", 			20, "BV_quadH2"],\
                       ["quad", 			20, "BV_quadJ1"],\
                       ["quad", 			20, "BV_quadJ2"],\
                       ["quad", 			20, "BV_quadB1"],\
                       ["quad", 			20, "BV_quadB2"],\
                       ["quad", 			20, "BV_quadB3"],\
                       ["quad", 			20, "BV_quadB4"],\
                       ["apc", 				20, "BV_crewapc"],\
                       ["apc", 				20, "BV_fobapc"],\
                       ["tank", 			20, "BV_fobtank"],\
                       ["boatAttack",		20, "BV_ba1"],\
                       ["boatAttack",		20, "BV_ba2"],\
                       ["boatSmall",		20, "BV_bs1"],\
                       ["boatSmall",		20, "BV_bs2"],\
                       ["sub",				20, "BV_sub1"],\
                       ["sub",				20, "BV_sub2"],\
                       ["boatBig",			20, "BV_bb1"]]

#define T_BA_tuvanaka [["npc",	["arsenal"],	"BA_leftVA"],\
                       ["npc",	["arsenal"], 	"BA_rightVA"],\
                       ["npc",	["support"], 	"BA_support"],\
                       ["obj",	["arsenal"], 	"BA_crewVA"],\
                       ["obj",	["arsenal"], 	"BA_heliVA"],\
                       ["obj",	["arsenal"], 	"BA_jetVA"],\
                       ["obj",	["arsenal"], 	"BA_fobVA"],\
                       ["obj",	["arsenal"], 	"BA_frVA"],\
                       ["obj",	["billboard"], 	"BA_leftBB"],\
                       ["obj",	["billboard"], 	"BA_rightBB"],\
                       ["obj",	["hos"], 		"BA_hos0"],\
                       ["obj",	["hos"], 		"BA_hos1"],\
                       ["obj",	["hos"], 		"BA_hos2"],\
                       ["obj",	["hos"], 		"BA_hos3"],\
                       ["obj",	["hos"], 		"BA_hos4"]]
