class vcomai {
	aiSkillEnabled = 1;
	debug = 0;
	useMarkers = 0;
	noAIForPlayerLeader = 1;
	staticGarrison = 1;
	hearingDistance = 500;
	callArtillery = 1;
	noPathing = 0;
	useSmoke = 1;
	grenadeProb = 20;
	mineLaying = 1;
	mineLayingProb = 40;
	disembark = 1;
	magLimit = 2;
	increaseAccuracy = 1;
	warnDistance = 1000;
	loopDelay = 30;
};
